name : mirror

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Mirroring Repository
              uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url:
                    git@github.com:EpitechPromo2026/B-CPP-500-TLS-5-1-rtype-mickael1.peireto.git
                ssh_private_key:                              # <-- use 'secrets' to pass credential information.
                    ${{ secrets.SSH_KEY }}
